@startuml AppLogic
state "AppLogic State" as test_app_logic_AppLogic_State {
  state "InGame" as test_app_logic_AppLogic_State_InGame
  state "MainMenu" as test_app_logic_AppLogic_State_MainMenu
  state "SplashScreen" as test_app_logic_AppLogic_State_SplashScreen
}

test_app_logic_AppLogic_State_InGame --> test_app_logic_AppLogic_State_MainMenu : EndGame
test_app_logic_AppLogic_State_MainMenu --> test_app_logic_AppLogic_State_InGame : LoadGame
test_app_logic_AppLogic_State_SplashScreen --> test_app_logic_AppLogic_State_MainMenu : SplashScreenFadedIn

test_app_logic_AppLogic_State_InGame : OnEnter → ShowGame
test_app_logic_AppLogic_State_InGame : OnExit → HideGame
test_app_logic_AppLogic_State_MainMenu : OnEnter → HideSplashScreen
test_app_logic_AppLogic_State_SplashScreen : OnEnter → ShowSplashScreen
test_app_logic_AppLogic_State_SplashScreen : OnSplashScreenSkipped() → HideSplashScreen

[*] --> test_app_logic_AppLogic_State_SplashScreen
@enduml