@startuml GameLogic
state "GameLogic State" as test_game_logic_GameLogic_State {
  state "Running" as test_game_logic_GameLogic_State_Running
  state "Starting" as test_game_logic_GameLogic_State_Starting
}

test_game_logic_GameLogic_State_Running --> test_game_logic_GameLogic_State_Running : EndGame
test_game_logic_GameLogic_State_Starting --> test_game_logic_GameLogic_State_Running : GameStarted

test_game_logic_GameLogic_State_Starting : OnEnter → StartGame

[*] --> test_game_logic_GameLogic_State_Starting
@enduml